package com.form;

import com.koneksi.UserID;
import com.model.model_kasir;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;


public class FormKasir extends javax.swing.JFrame {
    public DefaultTableModel tbl;
    String header[] = {"ID", "Kode Barang", "Nama Barang", "Harga", "Jumlah", "Total"};
    model_kasir model = new model_kasir();
    
    String ID = UserID.getUserLogin();
    
    public FormKasir() throws SQLException {
        initComponents();
        tbl = new DefaultTableModel(null, header);
        tblKasir.setModel(tbl);
        tblKasir.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        model.Tanggal(this);
        model.AutoNomor(this);
        model.AutoNomorKode(this);
        setLebarKolom();
        txtid_transaksi2.setVisible(false);
        txtkode_barang.requestFocus();
        txttotal.setText("0");
        this.getRootPane().setDefaultButton(btnOK);
        txtnama_kasir.setText(ID);
    }
    
    public void setColomnWidth(int kolom){
        DefaultTableColumnModel dt = (DefaultTableColumnModel) tblKasir.getColumnModel();
        TableColumn kolomtabel = dt.getColumn(kolom);
        int lebar = 0;
        int margin = 10;
        int a;
        
        TableCellRenderer render = kolomtabel.getHeaderRenderer();
        if (render == null) {
            render = tblKasir.getTableHeader().getDefaultRenderer();
        }
        Component kompo = render.getTableCellRendererComponent(tblKasir, kolomtabel.getHeaderValue(), false, false, 0, 0);
        lebar = kompo.getPreferredSize().width;
        for (a = 0; a < tblKasir.getRowCount(); a++) {
            render = tblKasir.getCellRenderer(a, kolom);
            kompo = render.getTableCellRendererComponent(tblKasir, tblKasir.getValueAt(a, kolom), false, false, a, kolom);
            int lebarKolom = kompo.getPreferredSize().width;
            lebar = Math.max(lebar, lebarKolom);
        }lebar = lebar + margin;
        kolomtabel.setPreferredWidth(lebar);
    }
    
    public void setLebarKolom(){
        int a;
        for (a = 0; a < tblKasir.getColumnCount(); a++) {
            setColomnWidth(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtid_transaksi = new javax.swing.JTextField();
        txtkembali = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        txtnama_kasir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtkode_barang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txttotal2 = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtkode_transaksi = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKasir = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtid_transaksi2 = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        txtbayar = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko Pendowo - Kasir");
        setPreferredSize(new java.awt.Dimension(935, 564));
        setSize(new java.awt.Dimension(951, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid_transaksi.setEditable(false);
        txtid_transaksi.setBackground(new java.awt.Color(248, 148, 6));
        txtid_transaksi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtid_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 14, 100, -1));

        txtkembali.setEditable(false);
        txtkembali.setBackground(new java.awt.Color(248, 148, 6));
        txtkembali.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtkembali.setForeground(new java.awt.Color(255, 255, 255));
        txtkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 514, 112, -1));

        btnHapus.setBackground(new java.awt.Color(242, 38, 19));
        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, 30));

        txtnama_kasir.setBackground(new java.awt.Color(248, 148, 6));
        txtnama_kasir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtnama_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 119, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUBTOTAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 414, -1, -1));

        jButton1.setBackground(new java.awt.Color(31, 58, 147));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        txtkode_barang.setBackground(new java.awt.Color(248, 148, 6));
        txtkode_barang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtkode_barang.setForeground(new java.awt.Color(255, 255, 255));
        txtkode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkode_barangActionPerformed(evt);
            }
        });
        txtkode_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkode_barangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkode_barangKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkode_barangKeyTyped(evt);
            }
        });
        jPanel1.add(txtkode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BAYAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 467, -1, -1));

        txtnama.setEditable(false);
        txtnama.setBackground(new java.awt.Color(248, 148, 6));
        txtnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 101, 360, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KEMBALI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 520, -1, -1));

        txtharga.setEditable(false);
        txtharga.setBackground(new java.awt.Color(248, 148, 6));
        txtharga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtharga.setForeground(new java.awt.Color(255, 255, 255));
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthargaKeyReleased(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 140, 30));

        txttotal2.setEditable(false);
        txttotal2.setBackground(new java.awt.Color(248, 148, 6));
        txttotal2.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        txttotal2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txttotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 415, 499, 134));

        txtjumlah.setBackground(new java.awt.Color(248, 148, 6));
        txtjumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtjumlah.setForeground(new java.awt.Color(255, 255, 255));
        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
        });
        jPanel1.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 60, 30));

        txtkode_transaksi.setEditable(false);
        txtkode_transaksi.setBackground(new java.awt.Color(248, 148, 6));
        txtkode_transaksi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtkode_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 42, 100, -1));

        btnOK.setBackground(new java.awt.Color(31, 58, 147));
        btnOK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 50, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Transaksi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 17, -1, -1));

        tblKasir.setBackground(new java.awt.Color(248, 148, 6));
        tblKasir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblKasir.setForeground(new java.awt.Color(255, 255, 255));
        tblKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKasirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKasir);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 882, 265));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Transaksi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        txtid_transaksi2.setEditable(false);
        txtid_transaksi2.setBackground(new java.awt.Color(44, 62, 80));
        txtid_transaksi2.setBorder(null);
        jPanel1.add(txtid_transaksi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 15, 80, -1));

        txttotal.setEditable(false);
        txttotal.setBackground(new java.awt.Color(248, 148, 6));
        txttotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 408, 112, -1));

        btnCari.setBackground(new java.awt.Color(31, 58, 147));
        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("List");
        btnCari.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 60, 30));

        txtbayar.setBackground(new java.awt.Color(248, 148, 6));
        txtbayar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtbayar.setForeground(new java.awt.Color(255, 255, 255));
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        jPanel1.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 461, 112, -1));

        txtTanggal.setEditable(false);
        txtTanggal.setBackground(new java.awt.Color(248, 148, 6));
        txtTanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 119, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kode Barang");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 72, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qty.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("User");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 931, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try {
            model.Simpan(this);
        } catch (SQLException ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtkode_barangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkode_barangKeyTyped
        
    }//GEN-LAST:event_txtkode_barangKeyTyped

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
        
    }//GEN-LAST:event_txtjumlahKeyReleased

    private void txtkode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkode_barangActionPerformed
        try {
            model.AddBarang(this);
        } catch (Exception ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtkode_barangActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        try {
            model.Kembalian(this);
            model.CetakStruk(this);
        } catch (Exception ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            dispose();
        }
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembaliActionPerformed
        
    }//GEN-LAST:event_txtkembaliActionPerformed

    private void tblKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKasirMouseClicked
        try {
            model.KlikTabel(this);
        } catch (Exception ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblKasirMouseClicked

    private void txthargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyReleased
        try {
            model.Simpan(this);
            
        } catch (SQLException ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txthargaKeyReleased

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        try {
            model.UbahJumlah(this);
        } catch (Exception ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
            new FormCariBarang().show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            model.Hapus(this);
        } catch (Exception ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FormMenuAwal().show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtkode_barangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkode_barangKeyReleased
        try {
            if (txtkode_barang.getText().equals("+")) {
                tblKasir.requestFocus();
                int lastRow = tblKasir.convertRowIndexToView(tbl.getRowCount()-1);
                tblKasir.setRowSelectionInterval(lastRow,lastRow);
                model.KlikTabel(this);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtkode_barangKeyReleased

    private void txtkode_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkode_barangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_END) {
            txtbayar.requestFocus();
        }
    }//GEN-LAST:event_txtkode_barangKeyPressed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormKasir().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormKasir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    public static javax.swing.JButton btnOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    public javax.swing.JTable tblKasir;
    public javax.swing.JTextField txtTanggal;
    public static javax.swing.JTextField txtbayar;
    public static javax.swing.JTextField txtharga;
    public javax.swing.JTextField txtid_transaksi;
    public javax.swing.JTextField txtid_transaksi2;
    public static javax.swing.JTextField txtjumlah;
    public static javax.swing.JTextField txtkembali;
    public static javax.swing.JTextField txtkode_barang;
    public javax.swing.JTextField txtkode_transaksi;
    public static javax.swing.JTextField txtnama;
    public javax.swing.JTextField txtnama_kasir;
    public static javax.swing.JTextField txttotal;
    public static javax.swing.JTextField txttotal2;
    // End of variables declaration//GEN-END:variables
}
